"use client";
import { useEffect, useState } from "react";
import * as pdfjsLib from "pdfjs-dist";
import { ToolShell } from "@/components/ToolShell";
import { FileDropzone } from "@/components/FileDropzone";
import { StatusCard } from "@/components/StatusCard";
import { downloadBlob } from "@/lib/pdf-utils";
import { PdfPreview } from "@/components/PdfPreview";

export default function PdfToImagesPage(){const [file,setFile]=useState<File|null>(null);const [status,setStatus]=useState("Upload one PDF to convert pages to PNG images.");const [mode,setMode]=useState("all");const [outputs,setOutputs]=useState<string[]>([]);useEffect(()=>{pdfjsLib.GlobalWorkerOptions.workerSrc=`https://unpkg.com/pdfjs-dist@${pdfjsLib.version}/build/pdf.worker.min.mjs`;},[]);async function run(){if(!file) return setStatus("Please upload a PDF.");setStatus("Rendering pages...");const data=await file.arrayBuffer();const doc=await pdfjsLib.getDocument({data}).promise;const pages=mode==="first"?[1]:Array.from({length:doc.numPages},(_,i)=>i+1);const out:string[]=[];for(const i of pages){const page=await doc.getPage(i);const viewport=page.getViewport({scale:2});const canvas=document.createElement("canvas");const ctx=canvas.getContext("2d");if(!ctx) continue;canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:ctx,viewport}).promise;const blob:Blob=await new Promise((resolve,reject)=>canvas.toBlob((b)=>b?resolve(b):reject(new Error("PNG conversion failed")),"image/png"));downloadBlob(blob,`pdfmantra-page-${i}.png`);out.push(canvas.toDataURL("image/png"));}setOutputs(out);setStatus(`Downloaded ${pages.length} PNG file(s).`);}return <ToolShell title="PDF to Images" description="Preview PDF and convert first or all pages to PNG."><div className="space-y-4"><FileDropzone label="Upload one PDF" accept="application/pdf,.pdf" onFiles={(f)=>setFile(f[0]||null)} /><PdfPreview file={file} maxPages={4} /><select value={mode} onChange={(e)=>setMode(e.target.value)} className="rounded-xl border px-3 py-2"><option value="all">Convert all pages</option><option value="first">First page only</option></select><button onClick={run} className="btn-primary">Convert & Download PNGs</button><div className="grid gap-3 sm:grid-cols-2">{outputs.map((src,i)=><img key={i} src={src} className="rounded border" alt={`Output ${i+1}`} />)}</div><StatusCard status={status} /></div></ToolShell>}
