"use client";
import { useMemo, useState } from "react";
import { ToolShell } from "@/components/ToolShell";
import { FileDropzone } from "@/components/FileDropzone";
import { StatusCard } from "@/components/StatusCard";
import { downloadBlob, rotatePdfByPage } from "@/lib/pdf-utils";
import { PdfPreview } from "@/components/PdfPreview";

export default function RotatePage(){const [file,setFile]=useState<File|null>(null);const [status,setStatus]=useState("Upload a PDF to rotate pages.");const [rot,setRot]=useState<number[]>([]);const pageCount=useMemo(()=>Math.max(rot.length,1),[rot]);const ensure=(i:number)=>setRot((p)=>{const c=[...p];while(c.length<=i)c.push(0);return c;});const rotatePage=(i:number,d:number)=>{ensure(i);setRot((p)=>{const c=[...p];c[i]=(((c[i]||0)+d)%360+360)%360;return c;});};const setAll=(d:number)=>setRot((p)=>p.map(()=>d));async function run(){if(!file) return setStatus("Please upload a PDF.");const blob=await rotatePdfByPage(file,rot);downloadBlob(blob,"pdfmantra-rotated.pdf");setStatus("Rotated PDF downloaded.");}return <ToolShell title="Rotate PDF" description="Preview pages and apply per-page/global rotation."><div className="space-y-4"><FileDropzone label="Upload one PDF" accept="application/pdf,.pdf" onFiles={(f)=>{setFile(f[0]||null);setRot([]);}} /><div className="flex flex-wrap gap-2"><button onClick={()=>setAll(90)} className="btn-secondary">Rotate all 90</button><button onClick={()=>setAll(180)} className="btn-secondary">Rotate all 180</button><button onClick={()=>setAll(270)} className="btn-secondary">Rotate all 270</button><button onClick={()=>setRot(rot.map(()=>0))} className="btn-secondary">Reset all</button></div><PdfPreview file={file} maxPages={8} /><div className="grid gap-2 sm:grid-cols-2">{Array.from({length:pageCount}).map((_,i)=><div key={i} className="rounded-xl border p-2 text-sm">Page {i+1}: {rot[i]||0}° <div className="mt-1 flex gap-1"><button onClick={()=>rotatePage(i,-90)} className="rounded border px-2">↺</button><button onClick={()=>rotatePage(i,90)} className="rounded border px-2">↻</button><button onClick={()=>rotatePage(i,-(rot[i]||0))} className="rounded border px-2">Reset</button></div></div>)}</div><button onClick={run} className="btn-primary">Apply Rotation & Download</button><StatusCard status={status} /></div></ToolShell>}
