import type {
  NormalizedRect,
  PdfPageIndex,
} from "../shared/types";

/**
 * PDFMantra Smart Highlight Engine Types
 * --------------------------------------------
 * These are the core domain models for the standalone highlight engine.
 *
 * Rules:
 * - Pure TypeScript only
 * - No React imports
 * - No UI-specific state
 * - Serializable for backend persistence
 * - Normalized 0..1 page-space is the canonical storage format
 */

export const HIGHLIGHT_LAYER_SCHEMA_VERSION = 1 as const;

export type HighlightLayerSchemaVersion =
  typeof HIGHLIGHT_LAYER_SCHEMA_VERSION;

export type HighlightLayerId = string;
export type SnappedRegionId = string;

/**
 * Color is intentionally stored as a string token.
 *
 * Current expected frontend format:
 * - HEX color strings such as "#FFE45E"
 *
 * This remains simple for:
 * - browser controls
 * - PDF export color parsing later
 * - backend persistence
 */
export type HighlightColor = string;

/**
 * Opacity should be stored in normalized range:
 * - 0 = invisible
 * - 1 = fully opaque
 */
export type HighlightOpacity = number;

/**
 * How the highlight annotation was created.
 */
export type HighlightCreationSource =
  | "text-drag-snap"
  | "ocr-drag-snap"
  | "freeform-drag"
  | "manual"
  | "imported";

/**
 * Source used to generate one precise snapped region.
 */
export type SnappedRegionSource =
  | "pdf-text"
  | "ocr-text"
  | "freeform"
  | "manual";

/**
 * Semantic granularity of the snapped region.
 *
 * This is intentionally richer than "rectangle" because the future engine
 * needs to distinguish:
 * - line snaps
 * - word snaps
 * - rough freeform fallback
 * - future object-aware regions
 */
export type SnappedRegionGranularity =
  | "word"
  | "line"
  | "selection"
  | "block"
  | "object"
  | "freeform";

/**
 * Styling contract for one logical highlight layer.
 *
 * Important:
 * - Style is stored once at layer level
 * - Regions under the same layer share the same color + opacity
 * - This supports multi-line text highlighting cleanly
 */
export interface HighlightStyle {
  readonly color: HighlightColor;
  readonly opacity: HighlightOpacity;
}

/**
 * A precise normalized region generated by the highlight snapper.
 *
 * Example:
 * - dragging over a sentence may produce 3 line regions
 * - dragging over a single word may produce 1 word region
 * - scanned PDF fallback may produce 1 freeform region
 *
 * All bounds are normalized 0..1 page-space values.
 */
export interface SnappedRegion {
  readonly id: SnappedRegionId;

  /**
   * Page index is kept here even though HighlightLayer also carries pageIndex.
   *
   * Reason:
   * - Snappers can return regions independently before a layer is assembled.
   * - OCR/text pipelines may process raw regions before final layer grouping.
   */
  readonly pageIndex: PdfPageIndex;

  /**
   * Final normalized region to render/export.
   */
  readonly bounds: NormalizedRect;

  /**
   * Optional original user drag/search area that produced this snapped result.
   *
   * This will help later with:
   * - debugging the snapper
   * - smart line targeting analysis
   * - future "refine selection" UX
   */
  readonly sourceBounds?: NormalizedRect;

  readonly source: SnappedRegionSource;
  readonly granularity: SnappedRegionGranularity;

  /**
   * Deterministic reading/rendering order inside a logical highlight layer.
   *
   * Example:
   * - top line = 0
   * - next line = 1
   */
  readonly readingOrder: number;

  /**
   * Optional extracted or OCR-recognized text represented by this region.
   *
   * This is domain data, not UI state.
   * It may be absent for freeform or object-like regions.
   */
  readonly text?: string;

  /**
   * Optional confidence score, mainly useful for OCR-generated regions.
   *
   * Expected range:
   * - 0 to 1
   */
  readonly confidence?: number;
}

/**
 * Canonical domain model for one logical highlight annotation.
 *
 * Important design choice:
 * - One user action may create multiple regions
 * - Those regions stay grouped inside one HighlightLayer
 *
 * This is ideal for:
 * - sentence highlights spanning multiple lines
 * - undo/redo
 * - delete-one-highlight behavior
 * - future backend persistence
 */
export interface HighlightLayer {
  readonly schemaVersion: HighlightLayerSchemaVersion;
  readonly id: HighlightLayerId;
  readonly kind: "highlight";

  /**
   * All regions inside one layer must belong to this same page.
   *
   * Multi-page selections should later become multiple HighlightLayer records,
   * one per page, instead of one cross-page mixed object.
   */
  readonly pageIndex: PdfPageIndex;

  readonly creationSource: HighlightCreationSource;
  readonly style: HighlightStyle;

  /**
   * Ordered precise regions that make up this single logical highlight.
   *
   * Empty layers should not be persisted.
   */
  readonly regions: readonly SnappedRegion[];
}

/**
 * Minimal creation input for building a logical highlight layer later.
 *
 * This is intentionally not used by React directly yet.
 * The future highlight engine will consume this shape internally when
 * converting snapped regions into a final HighlightLayer.
 */
export interface CreateHighlightLayerInput {
  readonly id: HighlightLayerId;
  readonly pageIndex: PdfPageIndex;
  readonly creationSource: HighlightCreationSource;
  readonly style: HighlightStyle;
  readonly regions: readonly SnappedRegion[];
}
